### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Qcat0214** [EsreverWoW/ClassicThreatMeter#1]
in Classic Beta server
lvl 17 hunter
When solo is in combat
this lua error has been going on all the time
https://upload.cc/i1/2019/06/04/EKLbil.png

**Comment by EsreverWoW** [comment]
I've pushed an update that potentially solves this issue for now. Would you mind letting me know if it persists after changes from the latest commit?

**Comment by EsreverWoW** [comment]
This particular error should be fixed now.
