### ISSUE TITLE
[BUG] Threat shows way too many digits making it hard to read in combat.

### ISSUE THREAD

**Issue by Zebrakiller** [EsreverWoW/ClassicThreatMeter#11]
### What steps will reproduce the problem?  
1.  Fight stuff
2.  I am a tank if that matters.
3.  

### What version of ClassicThreatMeter are you using? (Stating 'latest' is not useful)
1.04

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

[![Screenshot from Gyazo](https://gyazo.com/2fd0804306402fe3634784d48d2f8ba3/raw)](https://gyazo.com/2fd0804306402fe3634784d48d2f8ba3)

**Comment by EsreverWoW** [comment]
Would you be able to provide me a list of any other addons you might be running? I thought I had fixed this in 1.04. Can you confirm that you are running this version (I know you wrote it above, but I jut want to be sure).

**Comment by Zebrakiller** [comment]
Sure. I’ll check these in a few hours. Just woke up and I’m off to work. 

Very Respectfully,
Richard Zemore

**Comment by Zebrakiller** [comment]
When I am logged in WoW addon says I am using 1.02. But on Twitch it says I’m using 1.04 and there is no option to update my addon as twitch says it’s updated. 

Very Respectfully,
Richard Zemore

**Comment by EsreverWoW** [comment]
You may need to install manually at https://www.curseforge.com/wow/addons/classicthreatmeter/files/2775099 until I push a new update. The Twitch client tends to have the occasional hiccup.

**Comment by EsreverWoW** [comment]
Closing this, as it has been fixed. v1.05 has also been pushed to CurseForge and WoWInterface.
