### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Redhandedscrub** [EsreverWoW/ClassicThreatMeter#12]
The bonus threat modifier applied by a shamans Rockbiter Weapon is not tracked.
Attacked a mob with and without the imbue and same threat results were displayed.

**Comment by EsreverWoW** [comment]
I'll have this fixed in the next release (see: https://github.com/EsreverWoW/LibThreatClassic/commit/ce118ea4e70347fbfed3645bfe52f81b4195810f). Likely later tonight.

**Comment by EsreverWoW** [comment]
This has now been fixed in v1.05.
