### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RockOnzo** [EsreverWoW/ClassicThreatMeter#13]
### What steps will reproduce the problem?  
1.  apply righteous fury
2.  and lua error
3.  

### What version of ClassicThreatMeter are you using? (Stating 'latest' is not useful)
1.13.2

### Do you have an error log of what happened?
Message: ...s\ThreatClassic-1.0\ClassModules\Classic\Paladin.lua:146: attempt to perform arithmetic on local 'amt' (a string value)
Time: Mon Sep  2 06:53:40 2019
Count: 1
Stack: ...s\ThreatClassic-1.0\ClassModules\Classic\Paladin.lua:146: attempt to perform arithmetic on local 'amt' (a string value)
...s\ThreatClassic-1.0\ClassModules\Classic\Paladin.lua:146: in function `func'
...ore\Libs\ThreatClassic-1.0\ThreatClassModuleCore.lua:843: in function `calcBuffMods'
...ore\Libs\ThreatClassic-1.0\ThreatClassModuleCore.lua:589: in function `handler'
...ore\Libs\ThreatClassic-1.0\ThreatClassModuleCore.lua:690: in function `?'
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

Message: ...s\ThreatClassic-1.0\ClassModules\Classic\Paladin.lua:146: attempt to perform arithmetic on local 'amt' (a string value)
Time: Mon Sep  2 06:54:03 2019
Count: 2
Stack: ...s\ThreatClassic-1.0\ClassModules\Classic\Paladin.lua:146: attempt to perform arithmetic on local 'amt' (a string value)
...s\ThreatClassic-1.0\ClassModules\Classic\Paladin.lua:146: in function `?'
...ore\Libs\ThreatClassic-1.0\ThreatClassModuleCore.lua:626: in function `handler'
...ore\Libs\ThreatClassic-1.0\ThreatClassModuleCore.lua:690: in function `?'
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

Message: ...s\ThreatClassic-1.0\ClassModules\Classic\Paladin.lua:146: attempt to perform arithmetic on local 'amt' (a string value)
Time: Mon Sep  2 06:53:40 2019
Count: 1
Stack: ...s\ThreatClassic-1.0\ClassModules\Classic\Paladin.lua:146: attempt to perform arithmetic on local 'amt' (a string value)
...s\ThreatClassic-1.0\ClassModules\Classic\Paladin.lua:146: in function `func'
...ore\Libs\ThreatClassic-1.0\ThreatClassModuleCore.lua:843: in function `calcBuffMods'
...ore\Libs\ThreatClassic-1.0\ThreatClassModuleCore.lua:589: in function `handler'
...ore\Libs\ThreatClassic-1.0\ThreatClassModuleCore.lua:690: in function `?'
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by RockOnzo** [comment]
Message: ...s\ThreatClassic-1.0\ClassModules\Classic\Paladin.lua:146: attempt to perform arithmetic on local 'amt' (a string value)
Time: Mon Sep  2 06:54:03 2019
Count: 2
Stack: ...s\ThreatClassic-1.0\ClassModules\Classic\Paladin.lua:146: attempt to perform arithmetic on local 'amt' (a string value)
...s\ThreatClassic-1.0\ClassModules\Classic\Paladin.lua:146: in function `?'
...ore\Libs\ThreatClassic-1.0\ThreatClassModuleCore.lua:626: in function `handler'
...ore\Libs\ThreatClassic-1.0\ThreatClassModuleCore.lua:690: in function `?'
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

latest error

**Comment by EsreverWoW** [comment]
This is fixed as per https://github.com/EsreverWoW/LibThreatClassic/issues/4 which is included in version 1.05 of ClassicThreatMeter (in the process of being approved on CurseForge / WoWInterface).
