### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Evilmust** [EsreverWoW/ClassicThreatMeter#14]
I am using 1.05, and as of this version I am getting lua error message from wow.

Also, I am a tank, and I was using the nameplates inverted color options.

This does not work anymore.

Thank you!

**Comment by EsreverWoW** [comment]
I've just fixed this and pushed a 1.06 release to WoWI/CurseForge. This was introduced in the last update after some restructuring, but this update should resolve it.

**Comment by Evilmust** [comment]
Thanks so much! I am so happy I can tank better again! :D
