### ISSUE TITLE
lua error spam when grouped with just me using the latest version

### ISSUE THREAD

**Issue by towneh** [EsreverWoW/ClassicThreatMeter#2]
Message: ...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1127: Division by zero
Time: Wed Jun  5 01:43:40 2019
Count: 74
Stack: ...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1127: Division by zero
...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1127: in function `UnitDetailedThreatSituation'
Interface\AddOns\ClassicThreatMeter\core\core.lua:109: in function <Interface\AddOns\ClassicThreatMeter\core\core.lua:105>
Interface\AddOns\ClassicThreatMeter\core\core.lua:208: in function <Interface\AddOns\ClassicThreatMeter\core\core.lua:185>

Locals: player = "party1"
mob = "target"
playerGUID = "Player-4619-0000FBEC"
mobGUID = "Creature-0-4615-189-759-4283-0000F70F00"
threatPct = 100
maxThreat = 935.500000
threatValue = 0
isTanking = 1
status = 3
isMelee = true
(*temporary) = 1029.050000
(*temporary) = "target"
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Division by zero"
Lib = <table> {
 updaterFrame = <unnamed> {
 }
 DetailedThreatSituation = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1098
 myThreatMulti = <table> {
 }
 initialise = <unnamed> {
 }
 auraChecker = <unnamed> {
 }
 itemUpdateInfo = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:744
 groupMessageFrame = <unnamed> {
 }
 groupMemberTable = <table> {
 }
 talentItemUpdater = <unnamed> {
 }
 GUIDThreatTable = <table> {
 }
}

**Comment by EsreverWoW** [comment]
I've pushed an update that potentially solves this issue for now. Would you mind letting me know if it persists after changes from the latest commit?

**Comment by EsreverWoW** [comment]
This particular error should be fixed now.
