### ISSUE TITLE
more lua error whilst grouped and in combat with desolace npc

### ISSUE THREAD

**Issue by towneh** [EsreverWoW/ClassicThreatMeter#3]
Message: ...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1130: Division by zero
Time: Wed Jun  5 13:34:30 2019
Count: 6
Stack: ...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1130: Division by zero
...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1130: in function `UnitDetailedThreatSituation'
Interface\AddOns\ClassicThreatMeter\core\core.lua:109: in function <Interface\AddOns\ClassicThreatMeter\core\core.lua:105>
Interface\AddOns\ClassicThreatMeter\core\core.lua:208: in function <Interface\AddOns\ClassicThreatMeter\core\core.lua:185>

Locals: player = "party1"
mob = "target"
playerGUID = "Player-4619-0007AF7C"
mobGUID = "Creature-0-4615-1-29-4729-0003F6DA75"
threatPct = 100
maxThreat = 126.100000
threatValue = 0
isTanking = 0
status = 3
isMelee = true
(*temporary) = 138.710000
(*temporary) = "target"
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Division by zero"
Lib = <table> {
 updaterFrame = <unnamed> {
 }
 DetailedThreatSituation = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1098
 myThreatMulti = <table> {
 }
 initialise = <unnamed> {
 }
 auraChecker = <unnamed> {
 }
 itemUpdateInfo = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:744
 groupMessageFrame = <unnamed> {
 }
 groupMemberTable = <table> {
 }
 talentItemUpdater = <unnamed> {
 }
 GUIDThreatTable = <table> {
 }
}

![image](https://user-images.githubusercontent.com/25694892/58975900-0477b200-87be-11e9-9126-915f3c359f9f.png)

**Comment by towneh** [comment]
Further evidence when grouped, I get the following errors:

![image](https://user-images.githubusercontent.com/25694892/58983055-c7b3b700-87cd-11e9-9e42-be7b39e481db.png)

**Comment by towneh** [comment]
Message: ...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1130: Division by zero
Time: Wed Jun  5 19:57:51 2019
Count: 78
Stack: ...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1130: Division by zero
...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1130: in function `UnitDetailedThreatSituation'
Interface\AddOns\ClassicThreatMeter\core\core.lua:109: in function <Interface\AddOns\ClassicThreatMeter\core\core.lua:105>
Interface\AddOns\ClassicThreatMeter\core\core.lua:208: in function <Interface\AddOns\ClassicThreatMeter\core\core.lua:185>

Locals: player = "party1"
mob = "target"
playerGUID = "Player-4619-0000D725"
mobGUID = "Creature-0-4615-0-15-685-0000781093"
threatPct = 100
maxThreat = 1087.900000
threatValue = 0
isTanking = 0
status = 3
isMelee = true
(*temporary) = 1196.690000
(*temporary) = "target"
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Division by zero"
Lib = <table> {
 updaterFrame = <unnamed> {
 }
 DetailedThreatSituation = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1098
 myThreatMulti = <table> {
 }
 initialise = <unnamed> {
 }
 auraChecker = <unnamed> {
 }
 itemUpdateInfo = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:744
 groupMessageFrame = <unnamed> {
 }
 groupMemberTable = <table> {
 }
 talentItemUpdater = <unnamed> {
 }
 GUIDThreatTable = <table> {
 }
}

**Comment by towneh** [comment]
Message: ...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1130: Division by zero
Time: Wed Jun  5 19:57:49 2019
Count: 7
Stack: ...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1130: Division by zero
...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1130: in function `UnitDetailedThreatSituation'
Interface\AddOns\ClassicThreatMeter\core\core.lua:109: in function <Interface\AddOns\ClassicThreatMeter\core\core.lua:105>
Interface\AddOns\ClassicThreatMeter\core\core.lua:208: in function <Interface\AddOns\ClassicThreatMeter\core\core.lua:185>
[C]: in function `CastSpellByName'
Interface\FrameXML\ChatFrame.lua:1211: in function `?'
Interface\FrameXML\ChatFrame.lua:4607: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4288: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:2720: in function <Interface\FrameXML\ChatFrame.lua:2713>
[C]: in function `UseAction'
Interface\FrameXML\SecureTemplates.lua:340: in function `handler'
Interface\FrameXML\SecureTemplates.lua:618: in function `SecureActionButton_OnClick'
Interface\FrameXML\ActionButton.lua:100: in function <Interface\FrameXML\ActionButton.lua:94>
Interface\FrameXML\ActionButton.lua:136: in function `ActionButtonDown'
[string "ACTIONBUTTON2"]:2: in function <[string "ACTIONBUTTON2"]:1>

Locals: player = "party1"
mob = "target"
playerGUID = "Player-4619-0000D725"
mobGUID = "Creature-0-4615-0-15-685-0000781093"
threatPct = 100
maxThreat = 903.100000
threatValue = 0
isTanking = 0
status = 3
isMelee = true
(*temporary) = 993.410000
(*temporary) = "target"
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Division by zero"
Lib = <table> {
 updaterFrame = <unnamed> {
 }
 DetailedThreatSituation = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1098
 myThreatMulti = <table> {
 }
 initialise = <unnamed> {
 }
 auraChecker = <unnamed> {
 }
 itemUpdateInfo = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:744
 groupMessageFrame = <unnamed> {
 }
 groupMemberTable = <table> {
 }
 talentItemUpdater = <unnamed> {
 }
 GUIDThreatTable = <table> {
 }
}

**Comment by towneh** [comment]
Message: ...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1130: Division by zero
Time: Wed Jun  5 19:57:49 2019
Count: 8
Stack: ...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1130: Division by zero
...assicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1130: in function `UnitDetailedThreatSituation'
Interface\AddOns\ClassicThreatMeter\core\core.lua:109: in function <Interface\AddOns\ClassicThreatMeter\core\core.lua:105>
Interface\AddOns\ClassicThreatMeter\core\core.lua:208: in function <Interface\AddOns\ClassicThreatMeter\core\core.lua:185>
[C]: in function `CastSpellByName'
Interface\FrameXML\ChatFrame.lua:1211: in function `?'
Interface\FrameXML\ChatFrame.lua:4607: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4288: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:2720: in function <Interface\FrameXML\ChatFrame.lua:2713>
[C]: in function `UseAction'
Interface\FrameXML\SecureTemplates.lua:340: in function `handler'
Interface\FrameXML\SecureTemplates.lua:618: in function `SecureActionButton_OnClick'
Interface\FrameXML\MultiActionBars.lua:14: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR2BUTTON4"]:2: in function <[string "MULTIACTIONBAR2BUTTON4"]:1>

Locals: player = "party1"
mob = "target"
playerGUID = "Player-4619-0000D725"
mobGUID = "Creature-0-4615-0-15-685-0000781093"
threatPct = 100
maxThreat = 903.100000
threatValue = 0
isTanking = 0
status = 3
isMelee = true
(*temporary) = 993.410000
(*temporary) = "target"
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Division by zero"
Lib = <table> {
 updaterFrame = <unnamed> {
 }
 DetailedThreatSituation = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:1098
 myThreatMulti = <table> {
 }
 initialise = <unnamed> {
 }
 auraChecker = <unnamed> {
 }
 itemUpdateInfo = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\LibThreat-1.0\LibThreat-1.0.lua:744
 groupMessageFrame = <unnamed> {
 }
 groupMemberTable = <table> {
 }
 talentItemUpdater = <unnamed> {
 }
 GUIDThreatTable = <table> {
 }
}

**Comment by towneh** [comment]
latest version

Message: Interface\AddOns\ClassicThreatMeter\core\core.lua:226: attempt to concatenate a nil value
Time: Wed Jun  5 21:14:30 2019
Count: 1
Stack: Interface\AddOns\ClassicThreatMeter\core\core.lua:226: attempt to concatenate a nil value
Interface\AddOns\ClassicThreatMeter\core\core.lua:226: in function <Interface\AddOns\ClassicThreatMeter\core\core.lua:185>
[C]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals: self = ClassicThreatMeterBarFrame {
 0 = <userdata>
 backdrop = <unnamed> {
 }
 header = <unnamed> {
 }
 defaultPoint = <table> {
 }
 dragFrame = <unnamed> {
 }
 bars = <table> {
 }
 bg = <unnamed> {
 }
 headerText = <unnamed> {
 }
}
event = "PLAYER_TARGET_CHANGED"
instanceType = "party"
now = 1217213.149000
target = "targettarget"
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = "%s%s"
(*temporary) = "Threat"
(*temporary) = ": "
(*temporary) = nil
(*temporary) = "targettarget"
(*temporary) = nil
(*temporary) = "attempt to concatenate a nil value"
testMode = false
select = <function> defined =[C]:-1
C = <table> {
 visual = <table> {
 }
 font = <table> {
 }
 general = <table> {
 }
 sound = <table> {
 }
 frame = <table> {
 }
 backdrop = <table> {
 }
 bar = <table> {
 }
}
oldTime = 1217213.149000
wipe = <function> defined =[C]:-1
threatData = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
UpdateThreatData = <function> defined @Interface\AddOns\ClassicThreatMeter\core\core.lua:105
UpdateThreatBars = <function> defined @Interface\AddOns\ClassicThreatMeter\core\core.lua:154
format = <function> defined =[C]:-1
L = <table> {
 visual = <table> {
 }
 font = <table> {
 }
 general = <table> {
 }
 welcome = "Type /ctm for options."
 bar = <table> {
 }
 frame = <table> {
 }
 sound = <table> {
 }
 gui = <table> {
 }
}
bars = <table> {
 1 = <unnamed> {
 }
 2 = <unnamed> {
 }
 3 = <unnamed> {
 }
 4 = <unnamed> {
 }
 5 = <unnamed> {
 }
 6 = <unnamed> {
 }
 7 = <unnamed> {
 }
}

**Comment by EsreverWoW** [comment]
New update pushed.
