### ISSUE TITLE
[BUG] Talent in the bear does not count on maul

### ISSUE THREAD

**Issue by Loregon** [EsreverWoW/ClassicThreatMeter#34]
A mistake in calculating the threat, such a feeling that sometimes the addon forgets that the bear has talent for threat(*1.15) and bear threat(*1.3)
https://youtu.be/gVaT_FT7Y8o?t=1283
https://classic.warcraftlogs.com/reports/aD1JknG2b76mpQ8X#fight=63&source=2&type=damage-done
Shows 41k threats, but if you count by the logs
(20400+2600)*1.3*1.15*1.75+(1100+384)*1.15*1.3=62.4k
There are also debuffs...

In the last RT, a week ago. He only forgot about talent

### What version of ClassicThreatMeter are you using? (Stating 'latest' is not useful)
latest

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
Russian client, but noticed on streams the English guys have the same problem. 

Details plugin has the same problem...
https://youtu.be/oRjU0xyKBqk?t=2627
https://classic.warcraftlogs.com/reports/VXfcmL4haNGDA2d1#fight=last&type=damage-done&source=18
Shows 46.5k threats, but if you count by the logs
(19800+996)*1.3*1.15*1.75+392*1.3*1.15=55k

**Comment by aapoalas** [comment]
The bug is in ThreatClassic-1.0 library. Reporting it to CTM probably won't help much.
