### ISSUE TITLE
[Rogue] Error when interacting with NPCs and/or using stealth

### ISSUE THREAD

**Issue by towneh** [EsreverWoW/ClassicThreatMeter#5]
Message: ...er\lib\LibClassicThreat-1.0\LibClassicThreat-1.0.lua:947: attempt to index field '?' (a nil value)
Time: Tue Jul  2 21:08:59 2019
Count: 2
Stack: ...er\lib\LibClassicThreat-1.0\LibClassicThreat-1.0.lua:947: attempt to index field '?' (a nil value)
...er\lib\LibClassicThreat-1.0\LibClassicThreat-1.0.lua:947: in function <...er\lib\LibClassicThreat-1.0\LibClassicThreat-1.0.lua:941>

Locals: self = <unnamed> {
 0 = <userdata>
}
event = "UPDATE_SHAPESHIFT_COOLDOWN"
localClass = "Rogue"
class = "ROGUE"
(for index) = 1
(for limit) = 10
(for step) = 1
i = 1
icon = 136047
name = true
active = true
spellId = 1784
(*temporary) = <table> {
 rage = 5
 spell = 1
 global = 1
 healing = 0.500000
 range = 1.300000
 auraChanges = <table> {
 }
 stanceChanges = <table> {
 }
 spells = <table> {
 }
 mana = 0.500000
 aura = 1
 school = <table> {
 }
 melee = 0.800000
 energy = 5
 stance = 1
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
Lib = <table> {
 DetailedThreatSituation = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\LibClassicThreat-1.0\LibClassicThreat-1.0.lua:1206
 talentItemUpdater = <unnamed> {
 }
 callbacks = <table> {
 }
 myThreatMulti = <table> {
 }
 initialise = <unnamed> {
 }
 RegisterCallback = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 auraChecker = <unnamed> {
 }
 itemUpdateInfo = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\LibClassicThreat-1.0\LibClassicThreat-1.0.lua:769
 UnregisterCallback = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 GUIDThreatTable = <table> {
 }
 groupMessageFrame = <unnamed> {
 }
 groupMemberTable = <table> {
 }
 updaterFrame = <unnamed> {
 }
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
}
stanceList = <table> {
 DRUID = <table> {
 }
 WARRIOR = <table> {
 }
}
auraThreatList = <table> {
 26400 = <table> {
 }
 12685 = <table> {
 }
 25895 = <table> {
 }
 23604 = <table> {
 }
 28862 = <table> {
 }
 25780 = <table> {
 }
 1038 = <table> {
 }
 25908 = <table> {
 }
 21992 = <table> {
 }
 25892 = <table> {
 }
}

**Comment by towneh** [comment]
Also now get it repeatedly when attacking an NPC with sinister strike and not using stealth.

**Comment by towneh** [comment]
Also occurs when attempting to pickpocket or backstab a target whilst in stealth.

**Comment by towneh** [comment]
Specifically seems to error only when I have a unit targetted, and then I enter/exit stealth or use any abilities at all.

**Comment by EsreverWoW** [comment]
Mid-process of a substantial overhaul that will make this issue no longer pertinent.
