### ISSUE TITLE
[BUG] Lue Error on start

### ISSUE THREAD

**Issue by Tga123** [EsreverWoW/ClassicThreatMeter#6]
Date: 2019-08-27 14:37:21
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ClassicThreatMeter\locale\ruRU.lua line 8:
   attempt to index field 'gui' (a nil value)
Debug:
   ClassicThreatMeter\locale\ruRU.lua:8: in main chunk
Locals:
A = <table> {
 locale = "ruRU"
 addonName = "ClassicThreatMeter"
 version = "1.0"
}
C = <table> {
}
L = <table> {
 bar_defaultColor = "Custom Color"
 version_check = "Check Outdated"
 color_bad = "Bad"
 message_welcome = "Type /ctm for options."
 appearance = "Appearance"
 version_incompatible = "Not compatible!"
 visibility_hideInPvP = "Hide frame when in battlegrounds."
 bar_marker = "Player Threat in Red"
 color_good = "Good"
 frame_headerShow = "Show Header"
 font = "Font"
 warnings_sounds = "Enable sounds."
 bar_count = "Maximum Count"
 bar = "Bars"
 visibility_hideOOC = "Hide frame when out of combat."
 general_minimap = "Toggle minimap icon."
 font_shadow = "Dropshadow"
 message_leader = "You must be the group leader or have assist to do this."
 general_update = "Time (in seconds) between updates."
 gui_config = "Open Config"
 version_notify = "Notify Outdated"
 frame_scale = "Scale"
 frame_test = "Test Mode"
 nameplates_enable = "Enable threat coloring (only for Blizzard nameplates)."
 general_welcome = "Display welcome message when logging in."
 nameplates_invert = "Invert threat coloring (intended for tanks)."
 version_check_all = "Check All"
 frame = "Frame"
 bar_colorMod = "Color Modifier"
 gui_threat = "Threat"
 general_test = "Enable test mode."
 general = "General"
 color = "Colors"
 warnings_threshold = "Warning threshold (0-100%)."
 sound_pulledFile = "Pulled aggro sound file."
 font_family = "Name"
 message_outdated = "New version of CTM available! Please download the latest version."
 bar_height = "Height"
 bar_classColor = "Use Class Color"
 version_list_outdated = "Version Check: Outdated Clients"
 visibility = "Visibility"
 bar_texture = "Texture"
 frame_header = "Header"
 visibility_hideSolo = "Hide frame when not in a group."
 frame_width = "Width"
 color_neutral = "Neutral"
 message_incompatible = "CTM is out of date and will not be compatible for this group. Please upgrade immediately."
 sound_warningFile = "Warning sound file."
 warnings_visual = "Enable visual screen alerts."
 frame_bg = "Background"
 bar_descend = "Reverse Growth"
 bar_padding = "Padding"
 version_divider = "--------------------------------"
 frame_lock = "Lock"
 reset = "Reset to Defaults"
 font_style = "Style"
 font_size = "Size"
 version = "Version Check"
 nameplate_colors = "Threat Colors"
 bar_alpha = "Bar Alpha"
 warnings = "Warnings"
 version_list = "Version Check: All Clients"
 frame_headerColor = "Header Color"
 general_ignorePets = "Ignore threat from player pets."
 nameplates = "Nameplates"
}
_ = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'gui' (a nil value)"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  Ace3, v
  AdvancedInterfaceOptions, v1.3.0
  AtlasLootClassic, vv1.1.6-beta
  Auctionator, v8.1.0
  BagFreeSpaceCounter, v1.0.2
  BlizzMove, v1.9
  Chatter, v1.5.8
  ClassicAuraDurations, v
  ClassicAutoDismount, v1.01
  ClassicLFG, v1.0.0
  ClassicSpellActivations, v
  ClassicSpellRanks, v1.1
  ClassicThreatMeter, v1.0
  LibClassicItemSets10, v1.0.0
  BlizRuntimeLib_ruRU v1.13.2.11302 <none>
  (ck=1cf)

**Comment by EsreverWoW** [comment]
Fixed in 36938b2328e2bc1c146616732e478905b2413e1a. Will take a bit before it updates on WoWInterface/CurseForge, but it will be possible to download from here to replace the locale file affected.
