### ISSUE TITLE
[BUG]Pet Growl tracked even if resisted

### ISSUE THREAD

**Issue by Stryker159** [EsreverWoW/ClassicThreatMeter#9]
Running version 1.02 and have noticed that when a pets growl ability is used and is resisted by the mob the threat value for the skill is still being added to the meter. This is causing a discrepancy in the threat totals being displayed

**Comment by EsreverWoW** [comment]
I've noticed this also occurring with Torment from the Voidwalker. It's something I'm looking into.

**Comment by EsreverWoW** [comment]
Now fixed.
